# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

resources:
- repo: self

variables:
  tag: '1.0.$(Rev:r)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker Hub - Gabriel Meyer'
        repository: 'unisociesc/agendavoluntaria-api'
        command: 'build'
        Dockerfile: '**/Dockerfile.prod'
        buildContext: '.'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Push an image
      condition: |
        and ( succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        containerRegistry: 'Docker Hub - Gabriel Meyer'
        repository: 'unisociesc/agendavoluntaria-api'
        command: 'push'
        tags: '$(tag)'
    

    - task: CopyFilesOverSSH@0
      condition: |
        and ( succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        sshEndpoint: 'Servidor ProdCom'
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**/docker-compose.yml'
        targetFolder: '/var/www/api'
        readyTimeout: '20000'
    - task: SSH@0
      condition: |
        and ( succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        sshEndpoint: 'Servidor ProdCom'
        runOptions: 'inline'
        inline: 'docker stack deploy -c /var/www/api/docker-compose.yml agenda-api'
        readyTimeout: '20000'