# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr:
- master
- releases/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker Hub - Gabriel Meyer'
        repository: 'unisociesc/agendavoluntaria-api'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile.prod'
        buildContext: '.'
        tags: '$(tag)'