version: '3.7'

services:
  api:
    image: unisociesc/agendavoluntaria-api:#{tag}#
    build:
      context: .
      dockerfile: src/AgendaVoluntaria.Api/Dockerfile
    networks:
      - backend
      - frontend
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      update_config:
        delay: 15s
        parallelism: 5
        failure_action: rollback
      rollback_config:
        parallelism: 5
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`server.prodcom.com.br`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.api.loadbalancer.server.port=80"
  
  db:
    image: postgres:12.2
    environment: 
      - POSTGRES_PASSWORD=AgendaVoluntaria
      - POSTGRES_USER=AgendaVoluntaria
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/agenda/db

networks:
  frontend:
    external: true
  backend:
    external: true
  
