name: .NET Build For PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: docker image build -rm -f "./src/AgendaVoluntaria.Api/Dockerfile" -t agendavoluntaria:beta .
      
    #- name: Test
    # run: dotnet test --no-restore --verbosity normal
